### ISSUE TITLE
View Issue of 12 bits Dicom

### ISSUE THREAD

**Issue by zhang19** [Infogosoft/jsdicom#13]
This project is awesome.I admire the author's great effort on this project.
But when i load dicom file of 12 bits uncompressed image file,it seems like losing some bits data.The edge of shape is very sharp with lots of white spots.But is fine with 8 bits dicom file.Is this a bug?How and when can be fixed?
You can see it here.http://www.imagesocket.com/photos/guest/2461695

**Comment by daniel-lundin** [comment]
Yes, something doesn't look quite right there. Probably a bug of some sort. Will have a look at it and try to reproduce it.
Thanks for the feedback!

**Comment by zhang19** [comment]
You can download the dicom file from here.http://sharesend.com/6oiqp

**Comment by daniel-lundin** [comment]
That must be a different file, it looks fine to me:
http://minus.com/mXOfPHMkD

**Comment by zhang19** [comment]
I'm sorry.It seems like i have uploaded a wrong file.Here is the right ones.But they are 16 bits dicom files.Download here:http://min.us/mZTiDYrlD.

**Comment by daniel-lundin** [comment]
I think I know why it behaves the way it does. The Pixel Representation is in two complement which is not handled correctly. Will close this issue and open a new.
