### ISSUE TITLE
I can´t open any DICOM file

### ISSUE THREAD

**Issue by ghost** [Infogosoft/jsdicom#22]
Hi,

I can't open any dicom file. 
When I'm trying to open a .dcm file, it seems that is correct, but image don't appear in the window. 
Why it's happening this?
Could you help me?

Regards,
Manuel

**Comment by daniel-lundin** [comment]
Hi,

Do you know what kind of encoding the file has?
JPEG2000 for example is not supported.

Regards,
Daniel

**Comment by ghost** [comment]
Hi,

No, i don't know...
Do you know how i can see the encoding of my images?

Regards,
Manuel

**Comment by daniel-lundin** [comment]
Any decent dicom viewer will show you all tags of the file.
Check the Transfer Syntax UID tag.

or the command line tool dcmdump from dcmtk.

**Comment by ghost** [comment]
thanks 
regards,
Manuel
